build: off
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: ava
  template: AppVeyor CI automation
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Email
  to:
  - mysteryman@live.com.my
  subject: Build status of AVA GitHub Project
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
cache:
  - '%APPDATA%\npm-cache'
clone_depth: 1
skip_branch_with_pr: true
skip_commits:
  files:
    - '**/*.md'
configuration:
  - FreshDeps
  - LockedDeps
environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 6
    - nodejs_version: 4
matrix:
  fast_finish: true
  exclude:
    - configuration: FreshDeps
      nodejs_version: 6
    - configuration: FreshDeps
      nodejs_version: 4
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@^5.2.0
  - npm --version
  - git config core.symlinks true
  - git reset --hard
  - ps: if ($env:configuration -eq "FreshDeps") { Remove-Item package-lock.json }
  - if %configuration% == FreshDeps (npm install --prefer-online)
  - if %configuration% == LockedDeps (npm install --prefer-online)
test_script:
  - npm run test-win
